vuln/bookshop/urls.py
from django.urls import path

from .views import *

app_name = 'bookshop'
urlpatterns = [
    path('', BooksListView.as_view(), name='book-list'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>/', AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', AuthorCreateView.as_view(), name='create-author'),
    path('author/create-shitty/', ShittyAuthorCreateView.as_view(), name='shitty-create-author'),
    path('book/create/', BookCreateView.as_view(), name='create-book'),
]

vuln/vuln/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshop.urls', namespace='bookshop'))
]

vuln/bookshop/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=128)
    author = models.ForeignKey('bookshop.Author', on_delete=models.CASCADE, related_name='books')
    pages_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    personal_page = models.URLField(null=True, blank=True)

    @property
    def books_count(self):
        return self.books.count()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

vuln/bookshop/forms.py
from django.forms import ModelForm

from bookshop.models import Author


class ShittyAuthorForm(ModelForm):
    class Meta:
        model = Author
        exclude = []

vuln/bookshop/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from bookshop.forms import ShittyAuthorForm
from .models import Author, Book
from django.views.generic import CreateView, DetailView, ListView, View


__all__ = (
    'BooksListView', 'BookDetailView', 'AuthorDetailView', 'AuthorCreateView', 'BookCreateView',
    'ShittyAuthorCreateView',
)


class BooksListView(ListView):
    model = Book
    template_name = 'bookshop/books_list.html'

    def get_queryset(self):
        return self.model.objects.all().prefetch_related('author')


class BookDetailView(DetailView):
    model = Book


class AuthorDetailView(DetailView):
    model = Author


class AuthorCreateView(CreateView):
    model = Author
    fields = '__all__'
    template_name_suffix = '_create_form'
    success_url = '/'


class ShittyAuthorCreateView(View):
    form_class = ShittyAuthorForm

    def get(self, request: WSGIRequest) -> HttpResponse:
        form = self.form_class()
        return render(request, 'bookshop/author_create_form.html', {'form': form})

    def post(self, request: WSGIRequest) -> HttpResponseRedirect:
        Author.objects.create(
            first_name=request.POST['first_name'],
            last_name=request.POST['last_name'],
            personal_page=request.POST['personal_page'],
        )
        return HttpResponseRedirect(reverse('bookshop:book-list'))


class BookCreateView(CreateView):
    model = Book
    fields = '__all__'
    template_name_suffix = '_create_form'
    success_url = '/'

vuln/bookshop/templates/bookshop/author_create_form.html
{% extends "bookshop/base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

vuln/bookshop/templates/bookshop/author_detail.html
{% extends "bookshop/base.html" %}
{% block content %}
    <h1>{{ object.first_name}} {{ object.last_name }}</h1>
    {% if object.personal_page %}
    Personal page: <a href="{{ object.personal_page }}">{{ object.personal_page }}</a>
    {% endif %}
    <br/>
    Books:
    <ul>
        {% for book in object.books.all %}
        <li><a href="{% url 'bookshop:book-detail' book.pk %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

vuln/bookshop/templates/bookshop/base.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <a href="{% url 'bookshop:book-list' %}"><h1>Back to main page</h1></a>
        <button><a href="{% url 'bookshop:create-author' %}">Add new author</a></button>
        <button><a href="{% url 'bookshop:shitty-create-author' %}">Insecurely add new author</a></button>
        <button><a href="{% url 'bookshop:create-book' %}">Add new book</a></button>
        {% block content %}
        {% endblock content %}
    </body>
</html>

vuln/bookshop/templates/bookshop/book_create_form.html
{% extends "bookshop/base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

vuln/bookshop/templates/bookshop/book_detail.html
{% extends "bookshop/base.html" %}
{% block content %}
<br />
    Title: {{ object.title }} <br/>
    Pages: {{ object.pages }} <br/>
    Author: <a href="{% url 'bookshop:author-detail' object.author.pk %}">{{ object.author }}</a>
{% endblock content %}

vuln/bookshop/templates/bookshop/books_list.html
{% extends "bookshop/base.html" %}
{% block content %}
<h1>Books</h1>
<ul>
{% for book in object_list %}
    <li><a href="{% url 'bookshop:book-detail' book.id %}">{{ book.title }}</a> - <a href="{% url 'bookshop:author-detail' book.author.pk %}">{{ book.author.first_name }} {{ book.author.last_name }}</a></li>
{% empty %}
    <li>No books yet.</li>
{% endfor %}
</ul>
{% endblock content %}